Repository 42pakchoi/minishell, pull requests merged in 2022-04, with the labels that each got.

#23 issue/21 Update builtin `env`, `unset`, `export`, `exit` and `echo`
  includes/minishell.h
  src/builtin/echo.c
  src/builtin/env.c
  src/builtin/exit.c
  src/builtin/export.c
  src/builtin/unset.c
  src/util/var_util.c
Labels: builtin_cmd

#25 Fix prompt
  includes/minishell.h
  src/deal_command.c
  src/main.c
  src/parse_command.c
  src/util/cmd_util.c
Labels: prompt

#27 Fix save_history function
  includes/minishell.h
  src/history_func.c
  src/main.c
Labels: history

#32 Add builtin `cd`
  includes/minishell.h
  src/builtin/cd.c
Labels: builtin_cmd

#33 Add builtin `pwd`
  includes/minishell.h
  src/builtin/pwd.c
Labels: builtin_cmd

#36 Refactor command functions
  includes/minishell.h
  src/deal_command.c
  src/execute_nth_cmd.c
  src/find_command_path.c
  src/parse_env.c
  src/pipex.c
  src/split_command.c
  src/split_with_quote_flag.c
  src/util/cmd_util.c
  src/util/history_util.c
Labels: refactoring

#38 Fix parse_str_env function
  src/execute_nth_cmd.c
  src/parse_env.c
Labels: parsing

#44 Fix history functions
  src/util/history_util.c
Labels: bug, history

#50 Update builtin exit arg with sign
  src/builtin/exit.c
Labels: builtins

#52 Add function - is_valid_var_format
  includes/minishell.h
  src/util/var_util.c
Labels: util, env

#56 Update builtin cd when arg is ~
  src/builtin/cd.c
Labels: builtins

#69 Refactor execute_command
  includes/minishell.h
  src/deal_command.c
  src/deal_prompt.c
  src/execute_command.c
  src/main.c
  src/pipex.c
  src/util/cmd_util.c
  src/util/fd_util.c
  src/util/history_util.c
Labels: refactoring

#71 Refactor execute_command
  .gitignore
  src/exe_command.c
  src/exe_redir.c
  src/execute_command.c
  src/main.c
  src/util/fd_util.c
Labels: refactoring

#77 Refactor input, output redirection functions
  includes/minishell.h
  src/deal_command.c
  src/exe_command.c
  src/exe_redir.c
  src/main.c
  src/util/cmd_util.c
  src/util/fd_util.c
Labels: refactoring

#81 Fix parsing precess
  includes/minishell.h
  libft/Makefile
  libft/ft_strarr_join.c
  libft/ft_strarr_lcpy.c
  libft/ft_strarr_shift.c
  libft/libft.h
  src/deal_command.c
  src/util/cmd_util.c
Labels: parsing

#87 앞 부분이 같은 환경변수를 잘 못 찾는 이슈
  src/util/var_util1.c
Labels: env

#89 Refactor history variables from main function to global struct
  includes/minishell.h
  src/deal_command.c
  src/deal_prompt.c
  src/main.c
  src/signal.c
  src/util/history_util.c
Labels: history, refactoring

#94 Fix issue when length of argument is 1
  src/split_with_quote_flag.c
Labels: bug

#95 Update `cd` using `~/path`
  includes/minishell.h
  src/builtin/cd.c
  src/util/cd_util.c
Labels: builtins

#100 Implement exec_assign
  includes/minishell.h
  src/deal_command.c
  src/exec_command.c
  src/set_var.c
Labels: parsing

#101 Update prompt when HOME not exist
  src/main.c
Labels: prompt

#113 Update builtin export print sorted env list
  includes/minishell.h
  src/builtin/export.c
  src/util/export_util.c
Labels: builtins
